In [1]:
import numpy as np

## 0 dimension array (tensor)

In [2]:
a = np.array(2)

In [3]:
print(a)

2


In [4]:
a

array(2)

In [5]:
a.ndim

0

## 1 dimension array (tensor)

In [7]:
b = np.array([1,2,3,4,5])

In [8]:
print(b)

[1 2 3 4 5]


In [9]:
b

array([1, 2, 3, 4, 5])

In [10]:
b.ndim

1

In [13]:
b.shape

(5,)

## 2 Dimensional Array (tensor)


In [14]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
print (c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
c.ndim

2

In [18]:
c.shape

(3, 3)